services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: parking_management
    ports:
      - "25432:5432" # Maps host port 25432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

# Docker Volumes for data persistence
volumes:
  postgres_data: